### PR TITLE
#301: Visitor group criteria with GETA categories

### PR DESCRIPTION
**Pull request by tanvu-epi**

### CODE REVIEW

**Comment by davidknipe** [comment]
Is there potential for a null reference area here: https://github.com/episerver/Foundation/pull/304/commits/ebba5b4a6e5023486543a26363023e7d30ef012d#diff-61f1dee86cb93406fe01208723164e17R59? What would happen if this criterion was used on a page that didn't inherit from FoundationPageData? Would be better off if the page is PageData and also is ICategorizableContent?

**Comment by davidknipe** [comment]
Given Geta Categories is open source should we send this as a PR here rather than commit to Foundation? https://github.com/Geta/EpiCategories

**Comment by tanvu-epi** [comment]
> Is there potential for a null reference area here: [ebba5b4#diff-61f1dee86cb93406fe01208723164e17R59](https://github.com/episerver/Foundation/commit/ebba5b4a6e5023486543a26363023e7d30ef012d#diff-61f1dee86cb93406fe01208723164e17R59)? What would happen if this criterion was used on a page that didn't inherit from FoundationPageData? Would be better off to check if the page is PageData and also is ICategorizableContent?

I think all of page types in Foundation are inherited FoundationPageData (exclude container page) so that will be correct in Foundation. And I think we should apply this to Foundation and need some reviews before sending PR to GetaCategories.

**Comment by lunchin** [comment]
Added PR here https://github.com/Geta/EpiCategories/pull/26

**Pull request closed without merging**
