### PR TITLE
#404: Disable button when the variant is not available

### PR DESCRIPTION
**Pull request by tanvu-epi**

### CODE REVIEW

**Comment by davidknipe** [comment]
Does this change include the “out of stock” message in the colour / size drop down list as shown in the image?

**Comment by tanvu-epi** [comment]
> Does this change include the “out of stock” message in the colour / size drop down list as shown in the image?
Currently, we only check the current variant is available or not, so if include "out of stock" message in dropdown list then I think it need to check each variant of the product. Is that fine?

**Comment by davidknipe** [comment]
> > Does this change include the “out of stock” message in the colour / size drop down list as shown in the image?
> 
> Currently, we only check the current variant is available or not, so if include "out of stock" message in dropdown list then I think it need to check each variant of the product. Is that fine?

An example of how you can add the out of stock message to the dropdown list as shown here: https://gist.github.com/davidknipe/81ec1389a5f037fc0cb02bc34d1ca70e/revisions?diff=unified

Remember we need to make the out of stock message a translatable item :)

**Comment by tanvu-epi** [comment]
@davidknipe  would you like to mark "out of stock" message for all unavailable variants of the product (as below image) or current unavailable variant? 
image

**Comment by davidknipe** [comment]
> @davidknipe  would you like to mark "out of stock" message for all unavailable variants of the product (as below image) or current unavailable variant? 
> 
> image
> 
> 
> 
> The example codes you mentioned only mark the message for current unavailable variant.

Please mark all variants that are unavailable, as you have shown in the image. Thanks :)

**Comment by tanvu-epi** [comment]
> > @davidknipe  would you like to mark "out of stock" message for all unavailable variants of the product (as below image) or current unavailable variant?
> > image
> > The example codes you mentioned only mark the message for current unavailable variant.
> 
> Please mark all variants that are unavailable, as you have shown in the image. Thanks :)

Updated. Maybe performance will be suffer a bit when the product has many variants

**Pull request merged**
