### PR TITLE
#523: Videos as product assets

### PR DESCRIPTION
**Pull request by tanvu-epi**

### CODE REVIEW

**Comment by davidknipe** [comment]
Some initial feedback:

1. Video does not start and loop automatically on product page
2. If video is in position 1 of the media for a variant its not shown first
3. If video is only asset the product page doesn't display the video
4. If video is used then product is not clickable when displayed in listing

**Comment by tanvu-epi** [comment]
> Some initial feedback:
> 
> 1. Video does not start and loop automatically on product page
> 2. If video is in position 1 of the media for a variant its not shown first
> 3. If video is only asset the product page doesn't display the video
> 4. If video is used then product is not clickable when displayed in listing

updated

**Comment by davidknipe** [comment]
Not sure if its my specific build but cannot create pages/blocks. Try creating a page block and after hitting the page/block type screen is blank. Nothing in console or network:

image

**Comment by tanvu-epi** [comment]
> Not sure if its my specific build but cannot create pages/blocks. Try creating a page block and after hitting the page/block type screen is blank. Nothing in console or network:
> 
> image

Creating Page/Block only shows Required fields, I think  this's EPi's feature

**Comment by davidknipe** [comment]
> > Not sure if its my specific build but cannot create pages/blocks. Try creating a page block and after hitting the page/block type screen is blank. Nothing in console or network:
> 
> > 
> 
> > image
> 
> 
> 
> Creating Page/Block only shows Required fields, I think  this's EPi's feature

Hey thanks, seems the UX changed at some point as older versions of the UI used to pop a modal window at this point. Safe to ignore this :)

**Comment by davidknipe** [comment]
Another issue I found is that if you drag the product into a content area then the video is not shown, seems to be showing the first image

**Comment by davidknipe** [comment]
> > > Not sure if its my specific build but cannot create pages/blocks. Try creating a page block and after hitting the page/block type screen is blank. Nothing in console or network:
> > 
> > 
> > > 
> > 
> > 
> > > image
> > 
> > 
> > Creating Page/Block only shows Required fields, I think  this's EPi's feature
> 
> Hey thanks, seems the UX changed at some point as older versions of the UI used to pop a modal window at this point. For info this is an example of the old and new behaviour, not sure if this is a core thing or not but can work around it for now so we are safe to ignore:
> 
> **OLD UX**
> 
> old-ux
> 
> **NEW UX**
> 
> new-ux

For information I wasn't imaging something was up. Seems that Advanced.CMS.Forms makes content publish immediately on the create new screen. Removing it gets back to the modal and normal behaviour. Will report a separate issue.

**Pull request merged**
