### PR TITLE
#110: Top menu allows PageData

### PR DESCRIPTION
**Pull request by tanvu-epi**

### CODE REVIEW

**Comment by davidknipe** [comment]
Please do not merge this. When using a page in the menu and then viewing from edit mode the the edit mode URLs get cached in the menu. Suggest not caching the menu when in edit mode to avoid this. Will record a video later to demonstrate.

**Comment by tanvu-epi** [comment]
> Please do not merge this. When using a page in the menu and then viewing from edit mode the the edit mode URLs get cached in the menu. Suggest not caching the menu when in edit mode to avoid this. Will record a video later to demonstrate.

@davidknipe that issue is resolved in branch 121 (HeaderController and _Layout), I didn't fixed in this branch to prevent conflict code

**Comment by davidknipe** [comment]
I just tried this again with the referenced updated files and the issue still persists. To recreate:

Reset the application
Go straight to edit mode 
Drag a page in to the top menu
Publish
Log out
Notice that the page being linked is now the internal Episerver URL

To resolve only execute this line if **not** in edit mode:
https://github.com/episerver/Foundation/blob/3c2414a71d9d7c41f24e8afff83df1077fe74108/src/Foundation.Cms/ViewModels/Header/HeaderViewModelFactory.cs#L79

**Comment by tanvu-epi** [comment]
> I just tried this again with the referenced updated files and the issue still persists. To recreate:
> 
> Reset the application
> Go straight to edit mode
> Drag a page in to the top menu
> Publish
> Log out
> Notice that the page being linked is now the internal Episerver URL
> 
> To resolve only execute this line if **not** in edit mode:
> https://github.com/episerver/Foundation/blob/3c2414a71d9d7c41f24e8afff83df1077fe74108/src/Foundation.Cms/ViewModels/Header/HeaderViewModelFactory.cs#L79

yes, I have updated in branch 121

**Pull request merged**
